/** Defines interactions performed between canvas worker and the user */
export enum UserCanvasActionType {
    CANVAS_INITIALIZE_USER = "CANVAS_INITIALIZE_USER",
    CANVAS_INITIALIZE_MAIN_CANVAS = "CANVAS_INITIALIZE_MAIN_CANVAS",
    CANVAS_INITIALIZE_TEMPORARY_LAYER = "CANVAS_INITIALIZE_TEMPORARY_LAYER",
    
    CANVAS_CHANGE_SELECTED_SHAPE = "CANVAS_CHANGE_SELECTED_SHAPE",
    CANVAS_CHANGE_MOUSE_POSITION = "CANVAS_CHANGE_MOUSE_POSITION",
    CANVAS_CHANGE_DRAWING_PROPERTIES = "CANVAS_CHANGE_DRAWING_PROPERTIES",
    CANVAS_CHANGE_THEME_BASED_PROPERTIES = "CANVAS_CHANGE_THEME_BASED_PROPERTIES",

    CANVAS_EVENTS_ADDED = "CANVAS_EVENTS_ADDED",
    CANVAS_EVENTS_LOAD = "CANVAS_EVENTS_LOAD",
    CANVAS_EVENTS_DELETE_ALL = "CANVAS_EVENTS_DELETE_ALL",

    CANVAS_PLAYER_MODE_RENDER_EVENT = "CANVAS_PLAYER_MODE_RENDER_EVENT",
    CANVAS_PLAYER_MODE_CLEAR_ALL_EVENTS = "CANVAS_PLAYER_MODE_CLEAR_ALL_EVENTS",

}
